name: getTag
description: check who triggers the action and returns false or true if user is in allowed_users list
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}
  date_format:
    required: false
    default: "YYYYMMD"
  time_zone:
    required: false
    default: "America/New_York"
  prepend:
    required: false
    default: ''
  append:
    required: false
    default: ''
  append_prepend_separator:
    required: false
    default: '.'
  
outputs:
  newTag:
    description: newTag
runs:
  using: "node16"
  main: src/index.js